# Generated by Django 5.2.1 on 2025-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeusers',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customeusers',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customeusers',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeusers',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeusers',
            name='pincode',
            field=models.BigIntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customeusers',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
